server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: IdentityService
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/accounts/**


        - id: IdentityServiceAuth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**






        - id: ProfileService
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/profile/**

        - id: NotificationService
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notification/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
