server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - IdentityService
        - id: IdentityService-identityQuery
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/identity/**

#        ProfileService
        - id: ProfileService
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/profile/**
        #          filters:
        #            - RewritePath=/identityCommand/(?<remaining>.*), /$\{remaining}




        - id: NotificationService-profileCommand
          uri: http://localhost:8083
          predicates:
            - Path=/profileCommand/**
      #          filters:
      #            - RewritePath=/identityCommand/(?<remaining>.*), /$\{remaining}





#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#              allowedOrigins: "*"
#              allowedMethods: "*"
#              allowedHeaders: "*"

